/*
  File autogenerated by gengetopt version 2.22.5
  generated with the following command:
  gengetopt -i sboy.ggo --no-handle-help

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif

#include <getopt.h>

#include "cmdline.h"

const char *gengetopt_args_info_purpose = "Reads data from SMA SunnyBoy Inverters";

const char *gengetopt_args_info_usage = "Usage: " CMDLINE_PARSER_PACKAGE " [OPTIONS]...";

const char *gengetopt_args_info_description = "";

const char *gengetopt_args_info_detailed_help[] = {
  "  -h, --help                 Print help and exit",
  "      --detailed-help        Print help, including all details and hidden \n                               options, and exit",
  "      --full-help            Print help, including hidden options, and exit",
  "  -V, --version              Print version and exit",
  "\n Group: Display detail",
  "  -v, --verbosity[=level]    Set detail of output messages. With no argument \n                               defaults to normal verbosity  (possible \n                               values=\"quiet\", \"normal\", \"verbose\", \n                               \"detailed\" default=`normal')",
  "  -q, --quiet                For compatibility only. Quiet is the new default. \n                               Use verbosity (-v) as required.",
  "\nBluetooth MAC Address:",
  "      --address=mac_address  BT MAC address of inverter",
  "  The inverter address may be found using the 'hcitool scan' command on the \n  host computer",
  "      --device=mac_address   BT MAC address of host computer",
  "  The device address may be found using 'hcitool dev' command on the host \n  computer",
  "\nN.B. Bluetooth mac addresses must be 6 colon separated hex pairs e.g: \n00:01:FF:A6:42:9A",
  "\nHistory:",
  "      --history[=date]       Get history list for date from inverter.\n                               Default is today. Can also specify 'today' or \n                               'yesterday'.",
  "  -s, --start-time=time      Start time for history list.\n                               Default is before dawn.",
  "  -e, --end-time=time        End time/date for history list.\n                               Default is after dusk.",
  "\nOther options:",
  "  -b, --bt-power             Display Bluetooth power from inverter",
  "  -d, --dc-readings          Display DC current and voltage in inverter",
  "  -t, --set-time             Set inverter time to current time",
    0
};
static void
init_full_help_array(void)
{
  gengetopt_args_info_full_help[0] = gengetopt_args_info_detailed_help[0];
  gengetopt_args_info_full_help[1] = gengetopt_args_info_detailed_help[1];
  gengetopt_args_info_full_help[2] = gengetopt_args_info_detailed_help[2];
  gengetopt_args_info_full_help[3] = gengetopt_args_info_detailed_help[3];
  gengetopt_args_info_full_help[4] = gengetopt_args_info_detailed_help[4];
  gengetopt_args_info_full_help[5] = gengetopt_args_info_detailed_help[5];
  gengetopt_args_info_full_help[6] = gengetopt_args_info_detailed_help[6];
  gengetopt_args_info_full_help[7] = gengetopt_args_info_detailed_help[7];
  gengetopt_args_info_full_help[8] = gengetopt_args_info_detailed_help[8];
  gengetopt_args_info_full_help[9] = gengetopt_args_info_detailed_help[10];
  gengetopt_args_info_full_help[10] = gengetopt_args_info_detailed_help[12];
  gengetopt_args_info_full_help[11] = gengetopt_args_info_detailed_help[13];
  gengetopt_args_info_full_help[12] = gengetopt_args_info_detailed_help[14];
  gengetopt_args_info_full_help[13] = gengetopt_args_info_detailed_help[15];
  gengetopt_args_info_full_help[14] = gengetopt_args_info_detailed_help[16];
  gengetopt_args_info_full_help[15] = gengetopt_args_info_detailed_help[17];
  gengetopt_args_info_full_help[16] = gengetopt_args_info_detailed_help[18];
  gengetopt_args_info_full_help[17] = gengetopt_args_info_detailed_help[19];
  gengetopt_args_info_full_help[18] = gengetopt_args_info_detailed_help[20];
  gengetopt_args_info_full_help[19] = 0; 
  
}

const char *gengetopt_args_info_full_help[20];

static void
init_help_array(void)
{
  gengetopt_args_info_help[0] = gengetopt_args_info_detailed_help[0];
  gengetopt_args_info_help[1] = gengetopt_args_info_detailed_help[1];
  gengetopt_args_info_help[2] = gengetopt_args_info_detailed_help[2];
  gengetopt_args_info_help[3] = gengetopt_args_info_detailed_help[3];
  gengetopt_args_info_help[4] = gengetopt_args_info_detailed_help[4];
  gengetopt_args_info_help[5] = gengetopt_args_info_detailed_help[5];
  gengetopt_args_info_help[6] = gengetopt_args_info_detailed_help[7];
  gengetopt_args_info_help[7] = gengetopt_args_info_detailed_help[8];
  gengetopt_args_info_help[8] = gengetopt_args_info_detailed_help[10];
  gengetopt_args_info_help[9] = gengetopt_args_info_detailed_help[12];
  gengetopt_args_info_help[10] = gengetopt_args_info_detailed_help[13];
  gengetopt_args_info_help[11] = gengetopt_args_info_detailed_help[14];
  gengetopt_args_info_help[12] = gengetopt_args_info_detailed_help[15];
  gengetopt_args_info_help[13] = gengetopt_args_info_detailed_help[16];
  gengetopt_args_info_help[14] = gengetopt_args_info_detailed_help[17];
  gengetopt_args_info_help[15] = gengetopt_args_info_detailed_help[18];
  gengetopt_args_info_help[16] = gengetopt_args_info_detailed_help[19];
  gengetopt_args_info_help[17] = gengetopt_args_info_detailed_help[20];
  gengetopt_args_info_help[18] = 0; 
  
}

const char *gengetopt_args_info_help[19];

typedef enum {ARG_NO
  , ARG_STRING
  , ARG_ENUM
} cmdline_parser_arg_type;

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error);

static int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error);

const char *cmdline_parser_verbosity_values[] = {"quiet", "normal", "verbose", "detailed", 0}; /*< Possible values for verbosity. */

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->detailed_help_given = 0 ;
  args_info->full_help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->verbosity_given = 0 ;
  args_info->quiet_given = 0 ;
  args_info->address_given = 0 ;
  args_info->device_given = 0 ;
  args_info->history_given = 0 ;
  args_info->start_time_given = 0 ;
  args_info->end_time_given = 0 ;
  args_info->bt_power_given = 0 ;
  args_info->dc_readings_given = 0 ;
  args_info->set_time_given = 0 ;
  args_info->Display_detail_group_counter = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  FIX_UNUSED (args_info);
  args_info->verbosity_arg = verbosity_arg_normal;
  args_info->verbosity_orig = NULL;
  args_info->address_arg = NULL;
  args_info->address_orig = NULL;
  args_info->device_arg = NULL;
  args_info->device_orig = NULL;
  args_info->history_arg = NULL;
  args_info->history_orig = NULL;
  args_info->start_time_arg = NULL;
  args_info->start_time_orig = NULL;
  args_info->end_time_arg = NULL;
  args_info->end_time_orig = NULL;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{
  init_full_help_array(); 
  init_help_array(); 
  args_info->help_help = gengetopt_args_info_detailed_help[0] ;
  args_info->detailed_help_help = gengetopt_args_info_detailed_help[1] ;
  args_info->full_help_help = gengetopt_args_info_detailed_help[2] ;
  args_info->version_help = gengetopt_args_info_detailed_help[3] ;
  args_info->verbosity_help = gengetopt_args_info_detailed_help[5] ;
  args_info->quiet_help = gengetopt_args_info_detailed_help[6] ;
  args_info->address_help = gengetopt_args_info_detailed_help[8] ;
  args_info->device_help = gengetopt_args_info_detailed_help[10] ;
  args_info->history_help = gengetopt_args_info_detailed_help[14] ;
  args_info->start_time_help = gengetopt_args_info_detailed_help[15] ;
  args_info->end_time_help = gengetopt_args_info_detailed_help[16] ;
  args_info->bt_power_help = gengetopt_args_info_detailed_help[18] ;
  args_info->dc_readings_help = gengetopt_args_info_detailed_help[19] ;
  args_info->set_time_help = gengetopt_args_info_detailed_help[20] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(CMDLINE_PARSER_PACKAGE_NAME) ? CMDLINE_PARSER_PACKAGE_NAME : CMDLINE_PARSER_PACKAGE),
     CMDLINE_PARSER_VERSION);
}

static void print_help_common(void) {
  cmdline_parser_print_version ();

  if (strlen(gengetopt_args_info_purpose) > 0)
    printf("\n%s\n", gengetopt_args_info_purpose);

  if (strlen(gengetopt_args_info_usage) > 0)
    printf("\n%s\n", gengetopt_args_info_usage);

  printf("\n");

  if (strlen(gengetopt_args_info_description) > 0)
    printf("%s\n\n", gengetopt_args_info_description);
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_print_full_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_full_help[i])
    printf("%s\n", gengetopt_args_info_full_help[i++]);
}

void
cmdline_parser_print_detailed_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_detailed_help[i])
    printf("%s\n", gengetopt_args_info_detailed_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);
}

void
cmdline_parser_params_init(struct cmdline_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct cmdline_parser_params *
cmdline_parser_params_create(void)
{
  struct cmdline_parser_params *params = 
    (struct cmdline_parser_params *)malloc(sizeof(struct cmdline_parser_params));
  cmdline_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}


static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{

  free_string_field (&(args_info->verbosity_orig));
  free_string_field (&(args_info->address_arg));
  free_string_field (&(args_info->address_orig));
  free_string_field (&(args_info->device_arg));
  free_string_field (&(args_info->device_orig));
  free_string_field (&(args_info->history_arg));
  free_string_field (&(args_info->history_orig));
  free_string_field (&(args_info->start_time_arg));
  free_string_field (&(args_info->start_time_orig));
  free_string_field (&(args_info->end_time_arg));
  free_string_field (&(args_info->end_time_orig));
  
  

  clear_given (args_info);
}

/**
 * @param val the value to check
 * @param values the possible values
 * @return the index of the matched value:
 * -1 if no value matched,
 * -2 if more than one value has matched
 */
static int
check_possible_values(const char *val, const char *values[])
{
  int i, found, last;
  size_t len;

  if (!val)   /* otherwise strlen() crashes below */
    return -1; /* -1 means no argument for the option */

  found = last = 0;

  for (i = 0, len = strlen(val); values[i]; ++i)
    {
      if (strncmp(val, values[i], len) == 0)
        {
          ++found;
          last = i;
          if (strlen(values[i]) == len)
            return i; /* exact macth no need to check more */
        }
    }

  if (found == 1) /* one match: OK */
    return last;

  return (found ? -2 : -1); /* return many values or none matched */
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  int found = -1;
  if (arg) {
    if (values) {
      found = check_possible_values(arg, values);      
    }
    if (found >= 0)
      fprintf(outfile, "%s=\"%s\" # %s\n", opt, arg, values[found]);
    else
      fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}


int
cmdline_parser_dump(FILE *outfile, struct gengetopt_args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->detailed_help_given)
    write_into_file(outfile, "detailed-help", 0, 0 );
  if (args_info->full_help_given)
    write_into_file(outfile, "full-help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->verbosity_given)
    write_into_file(outfile, "verbosity", args_info->verbosity_orig, cmdline_parser_verbosity_values);
  if (args_info->quiet_given)
    write_into_file(outfile, "quiet", 0, 0 );
  if (args_info->address_given)
    write_into_file(outfile, "address", args_info->address_orig, 0);
  if (args_info->device_given)
    write_into_file(outfile, "device", args_info->device_orig, 0);
  if (args_info->history_given)
    write_into_file(outfile, "history", args_info->history_orig, 0);
  if (args_info->start_time_given)
    write_into_file(outfile, "start-time", args_info->start_time_orig, 0);
  if (args_info->end_time_given)
    write_into_file(outfile, "end-time", args_info->end_time_orig, 0);
  if (args_info->bt_power_given)
    write_into_file(outfile, "bt-power", 0, 0 );
  if (args_info->dc_readings_given)
    write_into_file(outfile, "dc-readings", 0, 0 );
  if (args_info->set_time_given)
    write_into_file(outfile, "set-time", 0, 0 );
  

  i = EXIT_SUCCESS;
  return i;
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

static void
reset_group_Display_detail(struct gengetopt_args_info *args_info)
{
  if (! args_info->Display_detail_group_counter)
    return;
  
  args_info->verbosity_given = 0 ;
  free_string_field (&(args_info->verbosity_orig));
  args_info->quiet_given = 0 ;

  args_info->Display_detail_group_counter = 0;
}

int
cmdline_parser (int argc, char **argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser_ext (int argc, char **argv, struct gengetopt_args_info *args_info,
                   struct cmdline_parser_params *params)
{
  int result;
  result = cmdline_parser_internal (argc, argv, args_info, params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser2 (int argc, char **argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = cmdline_parser_internal (argc, argv, args_info, &params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  int result = EXIT_SUCCESS;

  if (cmdline_parser_required2(args_info, prog_name, 0) > 0)
    result = EXIT_FAILURE;

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error)
{
  int error = 0;
  FIX_UNUSED (additional_error);

  /* checks for required options */
  
  /* checks for dependences among options */
  if (args_info->start_time_given && ! args_info->history_given)
    {
      fprintf (stderr, "%s: '--start-time' ('-s') option depends on option 'history'%s\n", prog_name, (additional_error ? additional_error : ""));
      error = 1;
    }
  if (args_info->end_time_given && ! args_info->history_given)
    {
      fprintf (stderr, "%s: '--end-time' ('-e') option depends on option 'history'%s\n", prog_name, (additional_error ? additional_error : ""));
      error = 1;
    }

  return error;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see cmdline_parser_params.check_ambiguity
 * @param override @see cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, const char *possible_values[],
               const char *default_value,
               cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;
  FIX_UNUSED (field);

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  if (possible_values && (found = check_possible_values((value ? value : default_value), possible_values)) < 0)
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: %s argument, \"%s\", for option `--%s' (`-%c')%s\n", 
          package_name, (found == -2) ? "ambiguous" : "invalid", value, long_opt, short_opt,
          (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: %s argument, \"%s\", for option `--%s'%s\n", 
          package_name, (found == -2) ? "ambiguous" : "invalid", value, long_opt,
          (additional_error ? additional_error : ""));
      return 1; /* failure */
    }
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_ENUM:
    if (val) *((int *)field) = found;
    break;
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };


  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}


int
cmdline_parser_internal (
  int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error = 0;
  struct gengetopt_args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  override = params->override;
  initialize = params->initialize;
  check_required = params->check_required;
  check_ambiguity = params->check_ambiguity;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "detailed-help",	0, NULL, 0 },
        { "full-help",	0, NULL, 0 },
        { "version",	0, NULL, 'V' },
        { "verbosity",	2, NULL, 'v' },
        { "quiet",	0, NULL, 'q' },
        { "address",	1, NULL, 0 },
        { "device",	1, NULL, 0 },
        { "history",	2, NULL, 0 },
        { "start-time",	1, NULL, 's' },
        { "end-time",	1, NULL, 'e' },
        { "bt-power",	0, NULL, 'b' },
        { "dc-readings",	0, NULL, 'd' },
        { "set-time",	0, NULL, 't' },
        { 0,  0, 0, 0 }
      };

      c = getopt_long (argc, argv, "hVv::qs:e:bdt", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
        
        
          if (update_arg( 0 , 
               0 , &(args_info->help_given),
              &(local_args_info.help_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "help", 'h',
              additional_error))
            goto failure;
          cmdline_parser_free (&local_args_info);
          return 0;
        
          break;
        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'v':	/* Set detail of output messages. With no argument defaults to normal verbosity.  */
        
          if (args_info->Display_detail_group_counter && override)
            reset_group_Display_detail (args_info);
          args_info->Display_detail_group_counter += 1;
        
          if (update_arg( (void *)&(args_info->verbosity_arg), 
               &(args_info->verbosity_orig), &(args_info->verbosity_given),
              &(local_args_info.verbosity_given), optarg, cmdline_parser_verbosity_values, "normal", ARG_ENUM,
              check_ambiguity, override, 0, 0,
              "verbosity", 'v',
              additional_error))
            goto failure;
        
          break;
        case 'q':	/* For compatibility only. Quiet is the new default. Use verbosity (-v) as required..  */
        
          if (args_info->Display_detail_group_counter && override)
            reset_group_Display_detail (args_info);
          args_info->Display_detail_group_counter += 1;
        
          if (update_arg( 0 , 
               0 , &(args_info->quiet_given),
              &(local_args_info.quiet_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "quiet", 'q',
              additional_error))
            goto failure;
        
          break;
        case 's':	/* Start time for history list.
        Default is before dawn..  */
        
        
          if (update_arg( (void *)&(args_info->start_time_arg), 
               &(args_info->start_time_orig), &(args_info->start_time_given),
              &(local_args_info.start_time_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "start-time", 's',
              additional_error))
            goto failure;
        
          break;
        case 'e':	/* End time/date for history list.
        Default is after dusk..  */
        
        
          if (update_arg( (void *)&(args_info->end_time_arg), 
               &(args_info->end_time_orig), &(args_info->end_time_given),
              &(local_args_info.end_time_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "end-time", 'e',
              additional_error))
            goto failure;
        
          break;
        case 'b':	/* Display Bluetooth power from inverter.  */
        
        
          if (update_arg( 0 , 
               0 , &(args_info->bt_power_given),
              &(local_args_info.bt_power_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "bt-power", 'b',
              additional_error))
            goto failure;
        
          break;
        case 'd':	/* Display DC current and voltage in inverter.  */
        
        
          if (update_arg( 0 , 
               0 , &(args_info->dc_readings_given),
              &(local_args_info.dc_readings_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "dc-readings", 'd',
              additional_error))
            goto failure;
        
          break;
        case 't':	/* Set inverter time to current time.  */
        
        
          if (update_arg( 0 , 
               0 , &(args_info->set_time_given),
              &(local_args_info.set_time_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "set-time", 't',
              additional_error))
            goto failure;
        
          break;

        case 0:	/* Long option with no short option */
          /* Print help, including all details and hidden options, and exit.  */
          if (strcmp (long_options[option_index].name, "detailed-help") == 0)
          {
          
          
            if (update_arg( 0 , 
                 0 , &(args_info->detailed_help_given),
                &(local_args_info.detailed_help_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "detailed-help", '-',
                additional_error))
              goto failure;
            cmdline_parser_free (&local_args_info);
            return 0;
          
          }
          /* Print help, including hidden options, and exit.  */
          else if (strcmp (long_options[option_index].name, "full-help") == 0)
          {
          
          
            if (update_arg( 0 , 
                 0 , &(args_info->full_help_given),
                &(local_args_info.full_help_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "full-help", '-',
                additional_error))
              goto failure;
            cmdline_parser_free (&local_args_info);
            return 0;
          
          }
          /* BT MAC address of inverter.  */
          else if (strcmp (long_options[option_index].name, "address") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->address_arg), 
                 &(args_info->address_orig), &(args_info->address_given),
                &(local_args_info.address_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "address", '-',
                additional_error))
              goto failure;
          
          }
          /* BT MAC address of host computer.  */
          else if (strcmp (long_options[option_index].name, "device") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->device_arg), 
                 &(args_info->device_orig), &(args_info->device_given),
                &(local_args_info.device_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "device", '-',
                additional_error))
              goto failure;
          
          }
          /* Get history list for date from inverter.
          Default is today. Can also specify 'today' or 'yesterday'..  */
          else if (strcmp (long_options[option_index].name, "history") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->history_arg), 
                 &(args_info->history_orig), &(args_info->history_given),
                &(local_args_info.history_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "history", '-',
                additional_error))
              goto failure;
          
          }
          
          break;
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */

  if (args_info->Display_detail_group_counter > 1)
    {
      fprintf (stderr, "%s: %d options of group Display detail were given. At most one is required%s.\n", argv[0], args_info->Display_detail_group_counter, (additional_error ? additional_error : ""));
      error = 1;
    }
  


  if (check_required)
    {
      error += cmdline_parser_required2 (args_info, argv[0], additional_error);
    }

  cmdline_parser_release (&local_args_info);

  if ( error )
    return (EXIT_FAILURE);

  return 0;

failure:
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
